[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # This plugin must be **removed or commented out** for export mode
  # If needed, delete or comment this whole block
